from enum import Enum, auto, unique


@unique
class CityId(Enum):
    ALGIERS = auto()
    ATLANTA = auto()
    BAGHDAD = auto()
    BANGKOK = auto()
    BEIJING = auto()
    BOGOTA = auto()
    BUENOS_ARIES = auto()
    CAIRO = auto()
    CHENNAI = auto()
    CHICAGO = auto()
    DELHI = auto()
    ESSEN = auto()
    HO_CHI_MINH_CITY = auto()
    HONG_KONG = auto()
    ISTANBUL = auto()
    JAKARTA = auto()
    JOHANNESBURG = auto()
    KARACHI = auto()
    KHARTOUM = auto()
    KINSHASA = auto()
    KOLKATA = auto()
    LAGOS = auto()
    LIMA = auto()
    LONDON = auto()
    LOS_ANGELES = auto()
    MADRID = auto()
    MANILA = auto()
    MEXICO_CITY = auto()
    MIAMI = auto()
    MILAN = auto()
    MONTREAL = auto()
    MOSCOW = auto()
    MUMBAI = auto()
    NEW_YORK = auto()
    OSAKA = auto()
    PARIS = auto()
    RIYADH = auto()
    SAN_FRANCISCO = auto()
    SANTIAGO = auto()
    SAO_PAULO = auto()
    SEOUL = auto()
    SHANGHAI = auto()
    ST_PETERSBURG = auto()
    SYDNEY = auto()
    TAIPEI = auto()
    TEHRAN = auto()
    TOKYO = auto()
    WASHINGTON = auto()